// lib/pdf/generate.ts
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { TwoFAClaims } from '@/types'

function t(str: string): string {
  if (!str) return ''
  const map: Record<string, string> = {
    'а':'a','б':'b','в':'v','г':'g','д':'d','е':'e','ж':'zh','з':'z',
    'и':'i','й':'y','к':'k','л':'l','м':'m','н':'n','о':'o','п':'p',
    'р':'r','с':'s','т':'t','у':'u','ф':'f','х':'h','ц':'ts','ч':'ch',
    'ш':'sh','щ':'sht','ъ':'a','ь':'','ю':'yu','я':'ya',
    'А':'A','Б':'B','В':'V','Г':'G','Д':'D','Е':'E','Ж':'Zh','З':'Z',
    'И':'I','Й':'Y','К':'K','Л':'L','М':'M','Н':'N','О':'O','П':'P',
    'Р':'R','С':'S','Т':'T','У':'U','Ф':'F','Х':'H','Ц':'Ts','Ч':'Ch',
    'Ш':'Sh','Щ':'Sht','Ъ':'A','Ь':'','Ю':'Yu','Я':'Ya',
  }
  return str.split('').map(c => map[c] ?? c).join('')
}

interface PDFInput {
  user: { email: string; full_name: string }
  request: {
    id: string
    type: string
    date_from: string
    date_to: string
    notes: string | null
    created_at: string
  }
  claims: TwoFAClaims
  ip: string
  ua: string
}

export async function generateRequestPDF(input: PDFInput): Promise<Uint8Array> {
  const { user, request, claims, ip, ua } = input

  const doc = await PDFDocument.create()
  const page = doc.addPage([595, 842])
  const { height } = page.getSize()

  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)

  const BLACK = rgb(0, 0, 0)
  const GRAY = rgb(0.4, 0.4, 0.4)
  const BLUE = rgb(0.3, 0.42, 0.96)
  const LINE = rgb(0.9, 0.9, 0.9)

  const drawText = (str: string, x: number, y: number, f = font, size = 10, color = BLACK) =>
    page.drawText(str, { x, y: height - y, font: f, size, color })

  const line = (y: number) =>
    page.drawLine({ start: { x: 50, y: height - y }, end: { x: 545, y: height - y }, thickness: 0.5, color: LINE })

  const section = (title: string, y: number) => {
    page.drawRectangle({ x: 50, y: height - y, width: 495, height: 18, color: rgb(0.95, 0.96, 1) })
    drawText(title, 55, y - 4, bold, 9, BLUE)
  }

  const row = (label: string, value: string, y: number) => {
    drawText(label, 55, y, font, 9, GRAY)
    drawText(value, 220, y, font, 9, BLACK)
    line(y + 8)
  }

  page.drawRectangle({ x: 0, y: height - 70, width: 595, height: 70, color: BLUE })
  drawText('HR PLATFORM', 50, 25, bold, 18, rgb(1, 1, 1))
  drawText('Official Request Document', 50, 48, font, 10, rgb(0.8, 0.85, 1))
  const docId = `REQ-${request.id.slice(0, 8).toUpperCase()}`
  drawText(docId, 545 - docId.length * 5.5, 35, bold, 10, rgb(1, 1, 1))

  section('EMPLOYEE DATA', 100)
  row('Full Name', t(user.full_name), 122)
  row('Email', user.email, 138)

  section('REQUEST DETAILS', 165)
  row('Type', request.type === 'vacation' ? 'Paid Leave' : 'Sick Leave', 187)
  row('From', request.date_from, 203)
  row('To', request.date_to, 219)
  const days = Math.ceil((new Date(request.date_to).getTime() - new Date(request.date_from).getTime()) / 86400000) + 1
  row('Days', String(days), 235)
  row('Notes', t(request.notes ?? '-'), 251)

  section('2FA AUTHENTICATION', 278)
  row('Method', (claims.method ?? 'totp').toUpperCase(), 300)
  row('Verified at', claims.verified_at ? new Date(claims.verified_at).toUTCString() : '-', 316)
  row('IP Address', ip, 332)
  row('Device', ua.length > 70 ? ua.slice(0, 70) + '...' : ua, 348)

  section('SYSTEM DATA', 375)
  row('Generated at', new Date().toUTCString(), 397)
  row('Timezone', 'UTC', 413)
  row('Document ID', request.id, 429)

  page.drawLine({ start: { x: 50, y: 50 }, end: { x: 545, y: 50 }, thickness: 0.5, color: LINE })
  page.drawText('This document was automatically generated by HR Platform with cryptographically verified data.',
    { x: 50, y: 35, font, size: 7, color: GRAY })
  page.drawText(`Generated: ${new Date().toISOString()}`, { x: 50, y: 22, font, size: 7, color: GRAY })

  return doc.save()
}
